# Generated by Django 4.1.2 on 2022-10-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kilometer", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("klassenstufe", models.IntegerField()),
                ("klasse", models.CharField(max_length=1)),
                ("lastseen", models.TimeField(auto_now=True)),
                ("kilometer", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Runde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("endtime", models.TimeField(auto_now_add=True)),
                ("time", models.TimeField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.student"
                    ),
                ),
            ],
        ),
    ]
