# Generated by Django 4.1.3 on 2022-11-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='klasse',
        ),
        migrations.RemoveField(
            model_name='student',
            name='klassenstufe',
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
