# Generated by Django 4.1.3 on 2022-11-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_key_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default='cgE9PC2WS6TPJFPLpko3j0wkhE1GJ4iU', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastseen',
            field=models.TimeField(),
        ),
    ]
