# Generated by Django 4.1.3 on 2022-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_key_key_alter_student_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default='nif0RTlxfbZHret18HPo4Hb2FmmpTWrH', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='runde',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastseen',
            field=models.FloatField(default=1667301632.2756817),
        ),
    ]
