# Generated by Django 4.1.3 on 2022-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0002_key_remove_student_klasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default='0fYbwAw1c7bk1RFzGaoDrzwPSU8Krjjf', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
