# Generated by Django 4.1.3 on 2022-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0004_alter_key_key_alter_student_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default='OoVMJQf4FRe0ITRfRkPKnyXo52rsPYYz', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastseen',
            field=models.CharField(default=1667301439.4652116, max_length=500),
        ),
    ]
