# Generated by Django 4.1.3 on 2022-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s', '0008_alter_key_key_alter_student_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default='UmWSmeS8GijKx4E2cFD3vlLjnKCR08Dq', max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='runde',
            name='time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastseen',
            field=models.FloatField(default=1667386166.2884328),
        ),
    ]
